@startuml

class Channel {
   
}

class EventBase  {

}

abstract class EventBases  {
    {abstract} EventBase *allocBase() = 0;
}

class MultiBase {

}

'指向谁，即继承谁。
'EventBases 继承 EventBase
EventBase --|> EventBases

'MultiBase 继承 EventBase
MultiBase --|> EventBases

@enduml